name: SwordMistwalker
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- FineWood:3:0:True
- Iron:15:10:True
- Eitr:10:5:True
- Wisp:3:1:True
- Coins:960:960:False
