name: StaffSkeleton
clonePrefabName: 
craftingStation: $piece_magetable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- BoneFragments:10:5:True
- Eitr:16:8:True
- TrophySkeleton:4:2:True
- Coins:960:960:False
