name: Recipe_ArmorMediumLegs_Ashlands
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
m_listSortWeight: 100
m_noCraftOnlyUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- LinenThread:15:10:True
- LoxPelt:4:2:True
- AskHide:10:5:True
- Upgrader6Armor:1:0:False
- Coins:1820:1820:False
