name: BowAshlands
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
m_listSortWeight: 100
m_noCraftOnlyUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Blackwood:10:5:True
- CharredBone:16:10:True
- FlametalNew:5:5:True
- BonemawSerpentTooth:5:5:True
- Upgrader6Weapon:1:0:False
- Coins:1820:1820:False
