name: Recipe_CrossbowRipper_Lightning
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
m_listSortWeight: 100
m_noCraftOnlyUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- CrossbowRipper:1:0:False
- FlametalNew:8:8:True
- GemstoneBlue:1:1:False
- Upgrader6Weapon:1:0:False
- Coins:1820:1820:False
