name: ArmorPaddedGreaves
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Iron:10:3:True
- LinenThread:20:10:True
- Coins:480:480:False
