name: CapeLinen
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- LinenThread:20:4:True
- Silver:1:0:True
- Coins:480:480:False
