name: AtgeirBlackmetal
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- FineWood:10:0:True
- BlackMetal:30:15:True
- LinenThread:5:5:True
- Coins:480:480:False
