name: BlackMetalCestus
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: $piece_forge
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- LeatherScraps:1:5:False
- BlackMetal:10:5:False
- Chain:4:10:False
- LinenThread:5:5:True
- Coins:480:480:False
