name: MaceNeedle
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- FineWood:5:0:True
- Iron:20:2:True
- Needle:5:2:True
- LinenThread:10:0:True
- Coins:480:480:False
