using System.Collections.Generic;
using HarmonyLib;

namespace PerspexModpackPatcher;

internal static class LegendsMuninPatch
{
    private static readonly Dictionary<string, string> Texts = new()
    {
        ["VL_Offerings"] = "You can inherit legendary powers by offering these configured gemstones:\nBerserker - Spinel Gemstone\nDruid - Emerald Gemstone\nDuelist - Jade Gemstone\nEnchanter - Garnet Gemstone\nMage - Ruby Gemstone\nMetavoker - Diamond Gemstone\nMonk - Amethyst Gemstone\nPriest - Topaz Gemstone\nRanger - Sulfur Gemstone\nRogue - Onyx Gemstone\nShaman - Humite Gemstone\nValkyrie - Sapphire Gemstone",
        ["VL_Mage"] = "Mage | Offering: Ruby Gemstone. Evocation improves offensive spells; Agility reduces their stamina costs.\nFire: Fireball deals 0.8 x RP fire damage; 10 stamina + 1 Fire Charge; 2s cooldown. Flame Nova is an area blast; 10 stamina + 3 Fire Charges; 40s cooldown. Meteor deals 2.0 x RP per meteor; 15 stamina to start plus 15 stamina per second while held and rising Fire Charge cost per meteor; cooldown scales with meteors.\nFrost: Ice Shard deals 0.4 x RP split pierce/frost, tripled against Frozen targets; 10 stamina + 1 Frost Charge; 0.5s cooldown. Frost Nova is an area freeze and push; 10 stamina + 3 Frost Charges; 20s cooldown. Blizzard rains frost shards; no direct stamina, 1 Frost Charge per second; cooldown scales with channel time.\nArcane: Elemental Mastery and Arcane Intellect are toggles paid in Arcane Charges, with no direct activation stamina. Arcane Intellect can convert Eitr costs to stamina. Eitr Shield absorbs hits using Eitr and Arcane Charges; stamina may be used if Arcane Intellect redirects Eitr costs.\nBlock + ability selects an affinity. Meditation converts time and about 10 stamina per second into charges; this remains intentionally expensive.",
        ["VL_Berserker"] = "Berserker | Offering: Spinel Gemstone.\nExecute (Discipline): empowers several weapon hits and stagger; 20 stamina; 60s cooldown.\nBerserk (Alteration): trades health for movement and attack power; restores stamina on hits; 0 stamina; 60s cooldown.\nDash (Discipline): 1.0 x weapon damage through enemies; 25 stamina; 10s cooldown.\nEquipment signature: dual-wield normal attacks cost the same stamina as a single weapon. Torch pairs do not count. All ability stamina costs are reduced by Agility.\nSit and press Dash to repair an equipped one- or two-handed weapon; Discipline improves repair efficiency. Repair consumes stamina and starts the Dash cooldown.",
        ["VL_Druid"] = "Druid | Offering: Emerald Gemstone.\nRegeneration (Alteration, Body): nearby healing over time; 15 stamina; 60s cooldown. Blocking crafts a Spirit Binding Vial using an Ancient Seed.\nVines/Roots (Conjuration, Body): channeled piercing vines; 20 stamina to start plus 20 stamina per second per vine created; 20s cooldown.\nRoot Defender (Conjuration): summons defenders and Drusquitos; 30 stamina; 120s cooldown. Blocking can enter Fenring form instead.\nFenring form changes the ability set and consumes Eitr after its grace period. Agility reduces ability stamina costs.",
        ["VL_Metavoker"] = "Metavoker | Offering: Diamond Gemstone.\nForce Wave (Evocation): block + attack knocks back enemies; 15 stamina; shares Replica cooldown.\nLight / Release (Illusion): summons or launches a light; 15 stamina; 20s cooldown.\nWarp (Evocation): teleport farther while held; 15 stamina to start plus 15 stamina per second; 6s cooldown. Excess distance deals lightning damage.\nReplica (Illusion): summons illusions of nearby enemies; 25 stamina; 30s cooldown.\nTranslocation (Evocation): Block + Ability 2 selects an online player. Go To moves you to them; Summon brings them to you. The other player must accept. Costs 25 stamina, reduced by Agility, on success. Cooldown: 600s, reduced by INT to 300s. During cooldown, one Thunderstone bypasses it and is consumed only on success. Cannot start in combat; portal item restrictions apply.\nReactive Armor (Abjuration): block + Light creates a shield; 20 stamina, then stamina is spent per absorbed damage; block + Warp cancels it. Safe Fall uses 36 stamina per second times its config while active. Agility reduces ability stamina costs.",
        ["VL_Duelist"] = "Duelist | Offering: Jade Gemstone.\nSeismic Slash (Discipline, Special): weapon-based area attack; 20 stamina; 30s cooldown.\nRiposte (Discipline): timed counter with a weapon and no shield; 15 stamina; 6s cooldown. A ranged counter moves behind the attacker.\nCoin Shot / Quick Shot (Discipline): 15 stamina per use; 10s cooldown. Coin Shot also consumes coins. Blocking can challenge a target to a duel for coins.\nAgility reduces ability stamina costs; skill level improves damage, not the Quick Shot stamina price.\nSit and press S. Slash to repair an equipped one-handed blade; Discipline improves repair efficiency. Repair consumes stamina and starts the S. Slash cooldown.",
        ["VL_Rogue"] = "Rogue | Offering: Onyx Gemstone.\nPoison Bomb (Alteration): area poison; 40 stamina; 30s cooldown. Crouching uses Smoke Bomb instead for 10 stamina.\nBackstab (Discipline, Special): weapon attack from behind; 25 stamina; 20s cooldown.\nFade (Illusion): marks and returns to a position; 10 stamina; 15s cooldown.\nThrowing Dagger spends its own resource with no direct stamina.\nDual daggers are the Rogue signature: with two one-handed Knives equipped, normal attacks cost the same stamina as a single knife. Agility reduces ability stamina costs.",
        ["VL_Priest"] = "Priest | Offering: Topaz Gemstone.\nHeal (Alteration, Body): immediate nearby heal followed by channeled pulses; 25 stamina to start plus 25 stamina per second; 30s cooldown. Blocking makes a Spirit Binding Vial from Bone Fragments.\nPurge (Evocation and Alteration, Body): nearby fire/spirit damage and ally healing; 20 stamina; 15s cooldown.\nSanctify (Evocation, Body): area fire, spirit and blunt strike; 20 stamina; 45s cooldown.\nAgility reduces ability stamina costs.",
        ["VL_Enchanter"] = "Enchanter | Offering: Garnet Gemstone.\nWeaken (Alteration): debuffs enemies; 15 stamina; 60s cooldown.\nCharm (Illusion): charms a target; 20 stamina; 60s cooldown.\nZone Charge (Abjuration): charges a biome field; 15 stamina to start plus 15 stamina per second while held; 600s cooldown. Sitting can repair an equipped staff instead. In Deep North, its buff prevents slipping and deep snow slowdown; one fatal hit consumes it and leaves you at 1 Health.\nZone Shock: Block + Zone Charge consumes an active biome buff to release damage proportional to its remaining time.\nWeapon and armor enchantments grant elemental effects and charges. Agility reduces ability stamina costs.\nSit and press Zone Charge to repair an equipped staff; Alteration improves repair efficiency. Repair consumes stamina and starts the Zone Charge cooldown. Block + Zone Charge releases the active biome buff as Zone Shock, even during cooldown. With no biome buff, a Thunderstone resets its cooldown.",
        ["VL_Monk"] = "Monk | Offering: Amethyst Gemstone.\nChi Strike / Meteor Punch (Discipline, Special): weapon-based chi attack; 3 Chi, no direct stamina; 1s cooldown. Block + Chi Strike activates Chi Power Up.\nFlying Kick (Discipline): repeated unarmed hits; 20 stamina; 6s cooldown.\nChi Blast / Psi Bolt (Discipline, Special): spends Chi for a spirit/blunt burst; no direct stamina; 1s cooldown.\nChi Slam / Impact and Surge spend Chi instead of direct stamina. Unarmed hits and blocks generate Chi normally. Agility reduces Flying Kick stamina only.\nBlock + Chi Strike activates Chi Power Up: spend 80% of maximum stamina for 1 Chi charge. It has its own cooldown: after three activations, wait 120 seconds. Chi Power Up works while Chi Strike is on cooldown.",
        ["VL_Shaman"] = "Shaman | Offering: Humite Gemstone.\nSpirit Shock / Spirit Bomb (Evocation, Body): nearby lightning/spirit damage and spirit drain; 15 stamina; 45s cooldown.\nChain Healing (Alteration, Body): block + Spirit Shock heals allies; 20 stamina; 30s cooldown.\nShell (Abjuration): grants allies elemental protection and spirit damage; 25 stamina; 120s cooldown. Blocking can make a Spirit Binding Vial with a Thunderstone.\nEnrage (Alteration): increases ally speed and stamina regeneration; 25 stamina; 60s cooldown.\nWater Glide consumes 18 stamina per second times its config while active. Agility reduces ability stamina costs.",
        ["VL_Valkyrie"] = "Valkyrie | Offering: Sapphire Gemstone.\nBulwark (Abjuration): reduces incoming damage and builds charges from blocks; 20 stamina; 60s cooldown.\nLeap / Impact (Discipline, Vigour): aerial area impact; 25 stamina; 15s cooldown.\nStagger (Discipline): nearby stagger wave; 15 stamina; 20s cooldown.\nHarpoon Pull (block + attack) spends 1 stored hitCount and no direct stamina. Shield Release (block + Leap with shield) spends stored hitCount and no direct stamina.\nAgility reduces ability stamina costs.\nSit and press Leap to repair an equipped shield; Discipline improves repair efficiency. Repair consumes stamina and starts the Leap cooldown.",
        ["VL_Ranger"] = "Ranger | Offering: Sulfur Gemstone.\nPower Shot (Discipline, Special): boosts several projectiles; 10 stamina for the buff, while normal shots still pay their weapon stamina; 60s cooldown. Blocking crafts arrows from wood.\nShadow Stalk (Discipline): stealth and movement speed; 15 stamina; 45s cooldown.\nShadow Wolf (Conjuration): summons a companion; 30 stamina; 600s cooldown. Food can heal an existing wolf for a food-dependent stamina cost; blocking dismisses it.\nAgility reduces ability stamina costs.\nSit and press Power Shot to repair an equipped bow or crossbow; Discipline improves repair efficiency. Repair consumes stamina and starts the Power Shot cooldown.",
    };

    internal static void Install(Harmony harmony)
    {
        harmony.Patch(AccessTools.Method(typeof(Player), "OnSpawned"),
            postfix: new HarmonyMethod(typeof(LegendsMuninPatch), nameof(Update)) { priority = Priority.Last });
        harmony.Patch(AccessTools.Method(typeof(Player), nameof(Player.ShowTutorial)),
            prefix: new HarmonyMethod(typeof(LegendsMuninPatch), nameof(Update)));
    }

    private static void Update()
    {
        if (Tutorial.instance?.m_texts == null) return;
        foreach (var tutorial in Tutorial.instance.m_texts)
        {
            if (tutorial != null && Texts.TryGetValue(tutorial.m_name, out var value))
                tutorial.m_text = value;
        }
    }
}
