name: BBH_PlainsLox_Quiver
clonePrefabName:
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap:
repairStation:
amount: 1
disabled: false
disabledUpgrade: false
m_listSortWeight: 100
m_noCraftOnlyUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FineWood:15:0:True
- SerpentScale:5:2:True
- LoxPelt:3:1:True
- Coins:480:480:False
