name: $custompiece_bucketbig
piecehammer: Hammer
m_name: $custompiece_bucketbig
sizeMultiplier: 1
m_description: ''
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Decor
categoryOrderBeforePrefab: 
minStationLevel: 1
disabled: false
adminonly: false
comfort:
  comfort: 1
  comfortGroup: Banner
  comfortObjectName: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
allowedInDeepSnow: false
requireDeepSnow: false
spaceRequirement: 0
repairPiece: false
isUpgrade: false
usage: Furniture
blockingPieces: []
canRockJade: false
wearNTearData:
  health: 400
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Normal
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Normal
    m_spirit: Normal
    m_nonPlayer: Normal
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
  materialType: Wood
  burnable: true
  snowDamageImmune: false
  outsideRequiredBiomeDamage: 25
  minToolTier: 0
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
shieldGenData: 
batteringRamData: 
build:
- Wood:5:0:True
- BronzeNails:2:0:True
