name: BoltBloodGold
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
m_listSortWeight: 100
m_noCraftOnlyUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Gold:1:1:True
- Frostwood:8:1:True
- Feathers:2:1:True
- Coins:3840:3840:False
