name: Recipe_SledgeAnchor
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_forge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Iron:38:18:True
- LeatherScraps:20:10:True
- Chain:2:1:True
- TrophySerpent:1:0:True
