name: KnifeChitin
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- FineWood:4:0:True
- Chitin:20:10:True
- LeatherScraps:2:0:True
- Coins:120:120:False
