name: AtgeirIron
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:10:0:True
- Iron:30:15:True
- LeatherScraps:2:1:True
- Coins:120:120:False
