name: HelmetIron
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Iron:20:5:True
- DeerHide:2:0:True
- Coins:120:120:False
