name: SwordIron
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:2:1:True
- Iron:20:10:True
- LeatherScraps:3:2:True
- Coins:120:120:False
