name: MaceIron
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:4:0:True
- Iron:20:10:True
- LeatherScraps:3:0:True
- Coins:120:120:False
