name: Lesser_Group_Healing
clonePrefabName: 
craftingStation: $pp_alchemy_table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Honey:2:0:True
- Dandelion:3:0:True
- Pukeberries:2:0:True
