name: Hellbroth_of_Thors_Fury_Charge
clonePrefabName: 
craftingStation: $pp_potion_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
requireOnlyOneIngredient: false
reqs:
- Hellbroth_of_Thors_Fury:1:0:True
