name: BackpackBlackForest
m_weight: 40.0
m_name: $vapok_mod_item_backpack_blackforest
m_description: >-
  $vapok_mod_item_backpack_blackforest_description


  <color=YELLOW>Requires Level 7</color>
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack: 
Secondary_Attack: 
Damage: 
Damage_Per_Level: 
Armor:
  armor: 0
  armorPerLevel: 0
FoodStats: 
Moddifiers:
  m_movementModifier: -0.02
  m_EitrRegen: 0
  m_BaseItemStaminaModifier: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats: 
m_maxStackSize: 1
m_canBeReparied: false
m_destroyBroken: false
m_dodgeable: false
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 0
m_knockback: 0
m_useDurability: false
m_useDurabilityDrain: 0
m_durabilityDrain: 0
m_maxDurability: 0
m_durabilityPerLevel: 0
m_equipDuration: 1
m_skillType: None
m_animationState: Unarmed
m_itemType: Shoulder
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects: []
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect: []
  Trail_Effect: []
