name: ArmorWarriorChest
clonePrefabName: null
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: null
repairStation: $piece_forge
amount: 1
disabled: false
disabledUpgrade: false
m_listSortWeight: 100
m_noCraftOnlyUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Boss_Crystal_5:3:0:False
- eitr:5:3:True
- ScaleHide:3:1:True
- Coins:960:480:False
