name: ArmorBarbarianBronzeHelmetJD
clonePrefabName: null
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: null
repairStation: $piece_forge
amount: 1
disabled: false
disabledUpgrade: false
m_listSortWeight: 100
m_noCraftOnlyUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Boss_Crystal_7:3:0:False
- Bronze:5:3:True
- DeerHide:2:0:True
- Coins:60:30:False
