name: Recipe_ShieldFlametalTower
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Blackwood:15:10:True
- FlametalNew:10:4:True
- AskHide:5:2:True
- Coins:960:960:False