name: ShieldBronzeBuckler
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Bronze:10:5:True
- Wood:4:1:True
- Coins:60:60:False
