name: Recipe_ShieldWoodTower_var2
clonePrefabName: NO
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Wood:10:5:True
- LeatherScraps:6:3:True
- Coins:30:30:False
