name: Recipe_ShieldBlackmetal_var1
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FineWood:10:10:True
- BlackMetal:8:4:True
- Chain:5:2:True
- Coins:480:480:False
