name: Recipe_ShieldBlackmetalTower_var3
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FineWood:15:10:True
- BlackMetal:10:4:True
- Chain:7:2:True
- Coins:480:480:False
