name: ShieldCarapaceBuckler
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Carapace:16:8:True
- ScaleHide:3:3:True
- Eitr:10:3:True
- Coins:960:960:False
