name: mmo_fermenter
piecehammer: Hammer
m_name: $magicferm
sizeMultiplier: 1
m_description: $magicferm_description
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_forge
piecehammerCategory: Crafting
minStationLevel: 1
amount: 1
disabled: true
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 1000
  damageModifiers:
    m_blunt: Resistant
    m_slash: Resistant
    m_pierce: Resistant
    m_chop: Resistant
    m_pickaxe: Normal
    m_fire: Immune
    m_frost: Immune
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData:
  fermDuration: 2400
  fermConversion:
  - FromName: mmo_mead_minor
    ToName: mmo_xp_drink1
    Amount: 3
    Remove: false
  - FromName: mmo_mead_med
    ToName: mmo_xp_drink2
    Amount: 3
    Remove: false
  - FromName: mmo_mead_greater
    ToName: mmo_xp_drink3
    Amount: 3
    Remove: false
sapData: 
build:
- FineWood:30:1:True
- Bronze:5:1:True
- Coins:200:1:True
