name: stone_cart
piecehammer: Hammer
m_name: $piece_stonecutter $tool_cart
sizeMultiplier: 1
m_description: $piece_stone_cart_description
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Crafty Carts
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 5000
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Weak
    m_frost: Resistant
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: false
  supports: true
  triggerPrivateArea: true
  materialType: Wood
  burnable: true
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
shieldGenData: 
batteringRamData: 
build:
- Wood:30:1:True
- Iron:2:1:True
- Stone:4:1:True
- BronzeNails:10:1:True
