name: questitem_scroll_black
clonePrefabName: questitem_scroll_black
craftingStation: Scribe Table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- LeatherScraps:1:0:True
- Feathers:1:0:False
- Coal:1:0:False
- Coins:30:0:False