name: piece_world_standing_blueprint_rune
piecehammer: Hammer
m_name: $piece_world_standing_blueprint_rune
sizeMultiplier: 1
m_description: $piece_world_standing_blueprint_rune_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $custom_sky_forge
piecehammerCategory: Furniture
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 300
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Normal
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Normal
    m_spirit: Normal
  noRoofWear: true
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- Uncut_Red_Stone:3:0:True
- Stone:5:0:True
