name: GemOrangeRestore
clonePrefabName: Uncut_Orange_Stone
craftingStation: $jc_transmution_table
minStationLevel: 1
maxStationLevelCap: 
repairStation: $jc_transmution_table
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Shattered_Orange_Crystal:12:1:True
- Resin:1:1:True
