name: BMP_FrostResist_Earring
clonePrefabName: 
craftingStation: $jc_transmution_table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Thunderstone:2:0:True
- Crystal:2:0:True
- FreezeGland:2:0:True
- Silver:4:0:True
- Coins:240:0:True
