name: GemOrangeShattered
clonePrefabName: Shattered_Orange_Crystal
craftingStation: $jc_transmution_table
minStationLevel: 1
maxStationLevelCap: 
repairStation: $jc_transmution_table
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Uncut_Orange_Stone:1:1:True
