name: GemPurpleShattered
clonePrefabName: Shattered_Purple_Crystal
craftingStation: $jc_transmution_table
minStationLevel: 1
maxStationLevelCap: 
repairStation: $jc_transmution_table
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Uncut_Purple_Stone:1:1:True
