name: BMP_FireResist_Earring
clonePrefabName: 
craftingStation: $jc_transmution_table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- TrophySurtling:2:0:True
- Ruby:2:0:True
- AncientSeed:2:0:True
- Iron:4:0:True
- Coins:120:0:True
