name: CL_Pole_Blue
piecehammer: Hammer
m_name: $CL_Pole_Blue
sizeMultiplier: 1
m_description: $CL_Pole_Blue_Description
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Misc
categoryOrderBeforePrefab: 
minStationLevel: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
allowedInDeepSnow: false
requireDeepSnow: false
spaceRequirement: 0
repairPiece: false
isUpgrade: false
usage: 0
blockingPieces: []
canRockJade: false
wearNTearData:
  health: 300
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Resistant
    m_frost: Resistant
    m_lightning: Resistant
    m_poison: Immune
    m_spirit: Immune
    m_nonPlayer: Normal
  noRoofWear: false
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
  materialType: Iron
  burnable: true
  snowDamageImmune: false
  outsideRequiredBiomeDamage: 25
  minToolTier: 0
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
shieldGenData: 
batteringRamData: 
build:
- Uncut_Blue_Stone:5:1:True
- Iron:2:1:True
