name: DandelionSeeds
clonePrefabName: DandelionSeeds
craftingStation: $piece_preptable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Dandelion:5:0:True