name: MushroomYellowSeeds
clonePrefabName: MushroomYellowSeeds
craftingStation: $piece_preptable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- MushroomYellow:5:0:True