name: BMP_SautedMeatMushroom_Recipe_Cauldron
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- MushroomYellow:1:0:True
- DeerMeat:1:0:True
- Thistle:1:0:True
- RawMeat:1:0:True
