name: BMP_MountainStew_Recipe_Cauldron
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- WolfMeat:3:0:True
- Carrot:3:0:True
- Turnip:3:0:True
- MushroomYellow:3:0:True
