name: BMP_MushroomPie_Recipe_Cauldron
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 4
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- MushroomYellow:2:0:True
- Mushroom:2:0:True
- SpiceForests:1:0:True
- Blueberries:2:0:True
