name: BMP_MushroomPuff_Recipe_Inventory
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Honey:1:0:True
- Mushroom:1:0:True
- Raspberry:3:0:True
- Dandelion:1:0:True
