name: MaceBronze
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:4:0:True
- Bronze:8:4:True
- LeatherScraps:3:0:True
- Coins:60:60:False
