name: Recipe_HelmetBerserker
clonePrefabName: NO
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BjornHide:5:2:True
- TrophyBjorn:1:0:True
- Coins:90:90:False
