name: SwordBronze
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:2:1:True
- Bronze:8:4:True
- LeatherScraps:2:1:True
- Coins:60:60:False
