name: questitem_ghostlyheart
clonePrefabName: questitem_ghostlyheart
craftingStation: $custom_sky_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Uncut_Purple_Stone:1:1:True
- Thunderstone:1:1:True
- YmirRemains:1:1:True
