name: Recipe_YmirRemains
clonePrefabName: YmirRemains
craftingStation: $custom_sky_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 6
disabled: false
requireOnlyOneIngredient: false
reqs:
- Boss_Crystal_1:1:0:False
- Wood:6:0:False
