name: Recipe_YmirRemains5
clonePrefabName: YmirRemains
craftingStation: $custom_sky_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 18
disabled: false
requireOnlyOneIngredient: false
reqs:
- Boss_Crystal_3:1:0:False
- Wood:6:0:False
