name: Recipe_YmirRemains3
clonePrefabName: YmirRemains
craftingStation: $custom_sky_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 12
disabled: false
requireOnlyOneIngredient: false
reqs:
- Boss_Crystal_4:1:0:False
- Wood:6:0:False
