name: Marketstone
clonePrefabName: Marketstone
craftingStation: $custom_sky_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Shattered_Yellow_Crystal:1:1:True
- Resin:1:1:True
- Thunderstone:1:1:True
- Coins:10:10:True
