name: GemMossAgateTransmute
clonePrefabName: Uncut_mossagate_Stone
craftingStation: $custom_sky_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Uncut_Green_Stone:1:1:True
- Wood:1:1:True
- Coins:10:10:False
