name: Recipe_translocatorCrystal02
clonePrefabName: translocatorCrystal02
craftingStation: $custom_sky_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Uncut_Blue_Stone:1:1:True
- Thunderstone:1:1:True
- YmirRemains:1:1:True
