name: GemHowliteTransmute
clonePrefabName: Uncut_howlite_Stone
craftingStation: $custom_sky_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Uncut_White_Stone:1:1:True
- Feathers:1:1:True
- Coins:10:10:False
