name: ShieldWood
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:10:5:True
- Resin:4:2:True
- LeatherScraps:4:2:True
- Coins:30:30:False
