name: KnifeFlint
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:2:0:True
- Flint:4:2:True
- LeatherScraps:2:0:True
- Coins:30:30:False
