name: Bow
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:10:5:True
- LeatherScraps:8:4:True
- DeerHide:0:1:True
- Coins:30:30:False
