name: SpearFlint
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:5:3:True
- Flint:10:5:True
- LeatherScraps:2:1:True
- Coins:30:30:False
